language: node_js

node_js:
  - "lts/*"
addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.npm
    - ~/node_modules
    - ~/.cache

install:
  - npm ci

script:
  - npm -v
